version: '3.4'
services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  virtuoso:
    ports:
      - "8891:8890"
    restart: "no"
  database:
    restart: "no"
  file:
    restart: "no"