PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

SELECT ?url
WHERE {
  GRAPH ?g {
    VALUES ?url { <https://leidinggevenden.lokaalbestuur.vlaanderen.be/legaal/cookieverklaring> <https://leidinggevenden.lokaalbestuur.vlaanderen.be/legaal/disclaimer> }
  }
}
