CONSTRUCT {
  ?s
    a <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie> ;
    ?p ?o .
}
WHERE {
  ?s
    a <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie> ;
    ?p ?o .
}
